-d \\Mac\Home\Documents\Projects\drone\impl\gwsynthesis\drone.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst \\Mac\Home\Documents\Projects\drone\src\drone.cst
-cfg \\Mac\Home\Documents\Projects\drone\impl\pnr\device.cfg
-sdc \\Mac\Home\Documents\Projects\drone\src\drone.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
