-d /media/psf/Projects/drone/impl/gwsynthesis/drone.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /media/psf/Projects/drone/new_cpu/drone.cst
-cfg /media/psf/Projects/drone/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
